import pandas as pd
import threading
from threading import Lock
from concurrent.futures import ThreadPoolExecutor, as_completed
import os
import torch
import re
import json
import argparse
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, GenerationConfig
from journey_configuer import load_pipeline, device, clean_output, generate_text_with_local_model_batch
import sys

# Ensure stdout is line-buffered so prints appear immediately on HPC nodes
try:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(line_buffering=True)
except Exception:
    # Best-effort: set PYTHONUNBUFFERED environment variable as fallback
    os.environ.setdefault("PYTHONUNBUFFERED", "1")

DIMENSION_LABELS = {
    'syn_admission_report': 'nota de admissão',
    'syn_discharge_report': 'nota de alta',
    'syn_full_journey': 'percurso clínico completo',
}


# Possible modelss
# google/gemma-4-12B-it
# utter-project/EuroLLM-9B-Instruct-2512
# mistralai/Ministral-3-14B-Instruct-2512
def load_model(model_name, config):
    config["MODEL_ID"] = model_name
    return load_pipeline(config)
"""
def load_model(model_name, config):
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    local_dir = os.path.join(BASE_DIR, "../../models", model_name)

    model_source = local_dir if os.path.exists(local_dir) else model_name

    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(model_source, use_fast=True)

    # Load the model (fallback to cpu if cuda not available)
    try:
        model = AutoModelForCausalLM.from_pretrained(model_source)
    except Exception as e:
        raise RuntimeError(f"Failed to load model {model_source}: {e}")

    # Create a text-generation pipeline bound to the correct device
    dev = device(config)
    device_map = "auto" if dev == "cuda" and torch.cuda.is_available() else "cpu"
    
    print(f"Loading model '{model_source}' on device '{dev}' with device_map='{device_map}'", flush=True)

    gen_pipeline = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        device_map=device_map,
        return_full_text=False,
        clean_up_tokenization_spaces=False,
    )

    return {"pipeline": gen_pipeline, "tokenizer": tokenizer}
"""

def generate_text_with_transformers_batch(model_obj, prompts: list, config=None) -> list:
    gen = model_obj["pipeline"]
    tok = model_obj["tokenizer"]
    cfg = config or {}
    
    prompts = [
        tok.apply_chat_template(
            [{"role": "user", "content": p}],
            tokenize=False,
            add_generation_prompt=True
        )
        for p in prompts
    ]

    max_new_tokens = int(cfg.get("MAX_TOKENS", cfg.get("MAX_TOKENS_PER_PROMPT", 512)))
    temperature = float(cfg.get("TEMPERATURE", 0.7))
    top_p = float(cfg.get("TOP_P", 0.9))
    top_k = int(cfg.get("TOP_K", 50))
    do_sample = temperature > 0.0

    results = []
    
    gen_config = GenerationConfig(
            max_new_tokens=max_new_tokens,
            do_sample=do_sample,
            temperature=temperature,
            top_p=top_p,
            top_k=top_k,
            repetition_penalty=1.15,
    )

    # Use the pipeline's batched interface when possible
    try:
        outputs = gen(
            prompts,
            generation_config=gen_config,
            return_full_text=False
        )

        for out in outputs:
            # `out` is usually a dict with 'generated_text'
            if isinstance(out, dict):
                text = out.get("generated_text") or out.get("text") or str(out)
            elif isinstance(out, list) and out:
                first = out[0]
                text = first.get("generated_text") if isinstance(first, dict) else str(first)
            else:
                text = str(out)
            results.append(text)

    except Exception:
        print("[WARNING] Batch generation failed, falling back to sequential generation.", flush=True)
        # Fallback: generate sequentially
        for prompt in prompts:
            out = gen(
                prompt,
                generation_config=gen_config,
                return_full_text=False
            )
            if isinstance(out, list) and out:
                item = out[0]
                text = item.get("generated_text") if isinstance(item, dict) else str(item)
            elif isinstance(out, dict):
                text = out.get("generated_text") or out.get("text") or str(out)
            else:
                text = str(out)
            results.append(text)

    return results
def _generate_single_prompt(index, case_report, synthetic_report, column_name):
    
    prompt = f"""
            SYSTEM: You are a specialist evaluator of hospital clinical records in European Portuguese. Your task is to evaluate a synthetic document generated by AI. You are NOT the system that generated this document. Answer in the JSON format specified below. Answer in European Portuguese.

            TASK: Evaluate the {DIMENSION_LABELS[column_name]} of the clinical report below.

            REFERENCE CASE REPORT:
            "{case_report}"

            SYNTHETIC REPORT TO BE EVALUATED:
            "{synthetic_report}"

            INSTRUCTIONS:
                1. Assign a score from 1 to 5 (5 = excellent).
                2. List up to 3 specific strengths (with citation from the text).
                3. List up to 3 specific problems (with location in the text).
                4. Indicate whether this report requires in-depth specialized review (yes/no) and why.

            Please respond ONLY in the following JSON format:
            {{
                "score": <int>,
                "strengths": ["...", "..."],
                "issues": ["...", "..."],
                "requires_deep_review": <bool>,
                "rationale": "<2-3 sentences>"
            }}
            """
    return index, prompt

def prompt_generation(model, df, config, column_name):
    # Load the CSV file into a DataFrame
    
    # Dictionary to store results and lock for thread-safe access
    results = {}
    lock = Lock()
    
    # Generate prompts using ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=32) as executor:
        futures = {
            executor.submit(_generate_single_prompt, i, 
                            df[config['CASE_REPORT_COLUMN_NAME']].iloc[i],
                            df[column_name].iloc[i], 
                            column_name
            ): i for i in df.index
        }
        
        for future in as_completed(futures):
            try:
                index, prompt = future.result()
                with lock:
                    results[index] = prompt
            except Exception as e:
                index = futures[future]
                with lock:
                    results[index] = ""
                print(f"[ERROR] Index {index}: {e}", flush=True)
    
    # Return prompts in original order
    prompts = [results[i] for i in df.index]
    
    print(f"Generated {len(prompts)} prompts for column '{column_name}'", flush=True)
    return prompts

def main():
    # Parse command line arguments
    parser = argparse.ArgumentParser(description="Evaluate synthetic clinical reports using LLM as a judge")
    parser.add_argument("--part", type=int, help="Part number for PMCPatients dataset (e.g., 1, 2, 3, 4)")
    parser.add_argument("--model", type=str, default="utter-project/EuroLLM-9B-Instruct-2512", help="Model name to use")
    args = parser.parse_args()
    
        

    json_file_path: str = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "config.json")
    with open(json_file_path, 'r') as json_file:
        config = json.load(json_file)
        
    print("config loaded", config, flush=True)
    
    # Modify the CSV path if part is specified
    base_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "output/Qwen/Qwen3-14B/PMCPatients")
    print(f"Base path for CSV files: {base_path}", flush=True)
    
    if args.part:
        config["CASE_REPORT_CSV_PATH"] = f"{base_path}_part{args.part}_cluster_ner_bert_bleu_score_evaluation.csv"
        part_suffix = f"_part{args.part}"
    else:
        config["CASE_REPORT_CSV_PATH"] = f"{base_path}_part1_cluster_ner_bert_bleu_score_evaluation.csv"
        part_suffix = ""
       
        
    print(f"Using CSV file: {config['CASE_REPORT_CSV_PATH']}", flush=True)
    
    model_name = args.model
    config["MODEL_ID"] = model_name
    model = load_model(model_name, config)
    
    print(f"Using model: {model_name} for evaluation", flush=True)
        
    # Load the CSV file
    df = pd.read_csv(config["CASE_REPORT_CSV_PATH"])
    print(f"Loaded {len(df)} records from {config['CASE_REPORT_CSV_PATH']}", flush=True)
    
    columns = [
        'syn_admission_report',
        'syn_discharge_report',
        'syn_full_journey'
    ]
        
    print(f"Loaded {len(df)} records")
    
    for column in columns:
        print(f"\nEvaluating {column}...", flush=True)
        prompts = prompt_generation(model, df, config, column)
        # Use the transformers-based batch generator implemented here
        results = generate_text_with_local_model_batch(model, prompts, config)
        cleaned_results = [clean_output(result) for result in results]
        df[f'evaluation_{column}'] = cleaned_results
        
        # Save with _judge suffix
        output_filename = f"{config['CASE_REPORT_CSV_PATH'][:-4]}_judge.csv"
        output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), output_filename)
        
        # Ensure output directory exists
        os.makedirs(os.path.dirname(output_path), exist_ok=True)    
        
        df.to_csv(output_path, index=False, encoding='utf-8-sig')
        print(f"Evaluation results for {column} saved to {output_path}", flush=True)
    

    

if __name__ == "__main__":
    main()
    